BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
             ${LAYERDIR}/recipes-*/*/*.bbappend"
BBFILE_COLLECTIONS += "xt-orin-domd"
BBFILE_PATTERN_xt-orin-domd = "^${LAYERDIR}/"
BBFILE_PRIORITY_xt-orin-domd = "10"
LAYERSERIES_COMPAT_xt-orin-domd = "scarthgap"
