# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-tegra-xen"
BBFILE_PATTERN_meta-tegra-xen = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-tegra-xen = "10"

LAYERDEPENDS_meta-tegra-xen = "core"
LAYERSERIES_COMPAT_meta-tegra-xen = "scarthgap"

LAYERDEPENDS_meta-tegra-xen = " \
    core \
    tegra \
    virtualization-layer \
"
